### PR TITLE
New Device

### PR DESCRIPTION
**Pull request by Manish4586**

### CODE REVIEW

**Comment by Demon000** [comment]
wat

**Comment by Manish4586** [comment]
I want to add Mi A2

**Comment by Demon000** [comment]
https://wiki.lineageos.org/submitting_device.html

**Comment by Manish4586** [comment]
Ok i will submit soon

**Comment by ItzLevvie** [comment]
Hey there, @Manish4586!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
