### PR TITLE
Added kyleproxx

### PR DESCRIPTION
**Pull request by AbitathaRoy**
Now up to the developers.

### CODE REVIEW

**Comment by divadsn** [comment]
Please go to Gerrit.

**Comment by axxx007xxxz** [comment]
Please don't.

**Comment by anirudhgupta109** [comment]
Someone explain to the guy that that's not how official devices work

**Comment by zifnab06** [comment]
https://review.lineageos.org, also this isn't anywhere close to how this works: please see https://wiki.lineageos.org/submitting_device.html

**Pull request closed without merging**
